import { Inter } from "next/font/google";
import "./globals.css";
import StateProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "+Kotitas",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (

        <html lang="en">
            <StateProvider>
                <body className={inter.className}>{children}</body>
            </StateProvider>
        </html>
    );
}

